db:
  image: postgres:9.3

bot:
  build: .
  links:
    - db
  volumes:
    - .:/code
  environment:
    DATABASE_URL: "postgres://postgres@db:5432/postgres"
    TWITTER_CONSUMER_KEY:
    TWITTER_CONSUMER_SECRET:
    TWITTER_ACCESS_TOKEN:
    TWITTER_ACCESS_TOKEN_SECRET:
    SILENT_MODE:
